### PR TITLE
Fix bug-221: Update taurus4 docs

### PR DESCRIPTION
**Pull request by cpascual**
Fix [bug-221](https://sf.net/p/tauruslib/tickets/221/) Adapt docs to changes in taurus4.
Note that docs for this branch are being automatically built in http://www.taurus-scada.org/en/bug-221/
Special attention should be put on adapting docs to:

- [ ] control-system agnosticism
- [ ] new name validators and related  should be mentioned
- [ ] TEP14 allowed value types should be explained
- [ ] Tango-centric explanations/examples should be reworded whenever possible
- [ ] non-tango examples should be added
- [ ] merging of Configuration into Attribute
- [ ] model names in examples, etc should be TEP3 compliant
- [ ] TEP14 allowed value types should be explained
- [ ] Examples for Eval should return Quantities
- [x] setuptools-based installation instructions
- [ ] new-style signals explained and used in examples
- [ ] searchpath based icon naming explained and used in examples
- [ ] TaurusApplication should be used in all the examples

### CODE REVIEW

**Comment by reszelaz** [comment]
Some comments:

- Link in the designer guide does not work: taurus.qt.qtgui.util.ui
- Difficulties in using scripts in the develop mode is not explained neither warned.
- Taurus web was removed but it is used in the "Users introduction"
- One example in "Users introduction" uses python taurusform.py instead of taurusform. Is it on purpose?
- In "Forms" Sardana examples on custom widgets could be better explained
- "Color meaning" is aligned to the center.
- Qualities warning and alarm are squashed to alarm only.

**Comment by cpascual** [comment]
>  - Link in the designer guide does not work: taurus.qt.qtgui.util.ui

Fixed

> - Difficulties in using scripts in the develop mode is not explained neither warned.

There are no difficulties now. It works well.

> - Taurus web was removed but it is used in the "Users introduction"

Fixed

> - One example in "Users introduction" uses python taurusform.py instead of taurusform. Is it on purpose?

Fixed

> - In "Forms" Sardana examples on custom widgets could be better explained

Done

> - "Color meaning" is aligned to the center.

Fixed

> - Qualities warning and alarm are squashed to alarm only.

Fixed

**Comment by cpascual** [comment]
For my part, I consider the changes finished. Please review last changes and, if ok, proceed to merge.

**Comment by reszelaz** [comment]
I still see problems with alignment of "Color meaning". I see it aligned to the center (both in my local build and in: http://www.taurus-scada.org/en/bug-221/users/ui/ui_colors.html)

**Comment by cpascual** [comment]
> I still see problems with alignment of "Color meaning".

Strange. Firefox renders it ok but chrome does not. It is likely related to some wrong html from the tables in this page. I suggest to treat it as a bug for the future

**Pull request merged**
